# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: Always
service:
  name: drg-landing-ui
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  annotationsProd:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "dragoons.gg,drg-landing-ui.jx-production.viserion.dragoons.gg,dragoons.io"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  annotationsStaging:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "drg-landing-ui.jx-staging.viserion.dragoons.gg,drg-landing-ui.jx-production.viserion.dragoons.gg,localhost,dragoons.io,dragoons.gg"
    nginx.ingress.kubernetes.io/enable-cors: "true"
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
production:
  enabled: false