apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        env:
        - name: ssl_certificate
          valueFrom:
            secretKeyRef:
              name: tls-drg-landing-ui
              key: tls.crt
        - name: ssl_certificate_key
          valueFrom:
            secretKeyRef:
              name: tls-drg-landing-ui
              key: tls.key      
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        # volumeMounts:
        # # name must match the volume name below
        # - name: secret-volume
        #   mountPath: /etc/secret-volume
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      # The secret data is exposed to Containers in the Pod through a Volume.
      # volumes:
      #   - name: secret-volume
      #     secret:
      #       secretName: tls-drg-landing-ui
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
