apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    fabric8.io/generated-by: exposecontroller
    ingress.kubernetes.io/service-upstream: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    ingress.bluemix.net/redirect-to-https: "true"
    # ingress.bluemix.net/server-snippets: |
    #   return 301 https://dragoons.gg$request_uri;
  name: drg-ingress
  namespace: jx-production
spec:
  rules:
  - host: dragoons.gg
    http:
      paths:
      - backend:
          serviceName: drgui
          servicePort: 80
        path: /app
      - backend:
          serviceName: drg-landing-ui
          servicePort: 80
        path: /
  tls:
  - hosts:
    - dragoons.gg
    secretName: tls-drg